// MockData.js

//FOR TESTING PURPOSES ONLY
//FOR TESTING PURPOSES ONLY
//FOR TESTING PURPOSES ONLY

const patients = [
  {
    id: 'https://i.imgur.com/3AlDV7v.png',
    name: 'John Doe',
    firstName: 'John',
    middleName: 'Robert',
    lastName: 'Doe',
    gender: 'Male',
    dateOfBirth: '1992-05-15',
    bloodGroup: 'A',
    rhFactor: '+',
    maritalStatus: 'Single',
    age: { years: 30, months: 10, days: 23 },
    phoneResidence: '123-456-7890',
    mobilePhone: '987-654-3210',
    emailAddress: 'john.doe@example.com',
    emergencyContactName: 'Jane Doe',
    emergencyContactPhoneNumber: '555-555-5555',
    family: ['Jane Doe', 'David Doe'],
    currentIllnesses: ['Fever', 'Cold', 'Cough'],
    previousIllnesses: ['Flu', 'Pneumonia'],
    specificAllergies: ['Peanuts', 'Penicillin'],
    currentMedications: ['Ibuprofen', 'Antihistamine'],
    pastMedications: ['Amoxicillin', 'Paracetamol'],
    labReports: [
      {
        report: 'Lab report text here',
        photo: 'https://i.imgur.com/kCtVNDR.png',
        radiologyVideo: 'https://www.youtube.com/embed/tW2SjlMGj0Q?si=ksQ6sKB0XmSz9z46',
        mriTracingImages: 'https://i.imgur.com/Fv45Hji.png'
      },
      {
        report: 'Lab report text here',
        photo: 'https://i.imgur.com/kCtVNDR.png',
        radiologyVideo: 'https://www.youtube.com/embed/tW2SjlMGj0Q?si=ksQ6sKB0XmSz9z46',
        mriTracingImages: 'https://i.imgur.com/Fv45Hji.png'
      }
    ],
    xRays: ['https://i.imgur.com/onW1Xuv.png', 'https://i.imgur.com/KcsHQbA.png'],
    doctorVisits: ['2022-01-05T08:00:00Z', '2022-02-15T09:30:00Z'],
    vaccinations: ['2022-03-20T10:45:00Z', '2022-04-10T11:15:00Z'],
    appointmentTimes: ['2022-05-15T12:30:00Z', '2022-06-25T13:00:00Z']
  },
  {
    id: 'https://i.imgur.com/3AlDV7v.png',
    name: 'Jane Smith',
    firstName: 'Jane',
    middleName: 'Emily',
    lastName: 'Smith',
    gender: 'Female',
    dateOfBirth: '1997-10-25',
    bloodGroup: 'AB',
    rhFactor: '-',
    maritalStatus: 'Married',
    age: { years: 25, months: 7, days: 30 },
    phoneResidence: '555-123-4567',
    mobilePhone: '555-987-6543',
    emailAddress: 'jane.smith@example.com',
    emergencyContactName: 'John Smith',
    emergencyContactPhoneNumber: '555-555-5555',
    family: ['John Smith', 'Emily Smith'],
    currentIllnesses: ['Headache', 'Fever', 'Sore Throat'],
    previousIllnesses: ['Sinusitis', 'Tonsillitis'],
    specificAllergies: ['Dust', 'Pollen'],
    currentMedications: ['Acetaminophen', 'Antibiotics'],
    pastMedications: ['Aspirin', 'Antacids'],
    labReports: [
      {
        report: 'Lab report text here',
        photo: 'https://i.imgur.com/kCtVNDR.png',
        radiologyVideo: 'https://www.youtube.com/embed/tW2SjlMGj0Q?si=ksQ6sKB0XmSz9z46',
        mriTracingImages: 'https://i.imgur.com/Fv45Hji.png'
      }
    ],
    xRays: ['https://i.imgur.com/onW1Xuv.png', 'https://i.imgur.com/KcsHQbA.png'],
    doctorVisits: ['2022-01-10T08:00:00Z', '2022-02-20T09:30:00Z'],
    vaccinations: ['2022-03-25T10:45:00Z', '2022-04-15T11:15:00Z'],
    appointmentTimes: ['2022-05-20T12:30:00Z', '2022-06-30T13:00:00Z']
  },
  {
    id: 'https://i.imgur.com/3AlDV7v.png',
    name: 'Michael Johnson',
    firstName: 'Michael',
    middleName: 'Christopher',
    lastName: 'Johnson',
    gender: 'Male',
    dateOfBirth: '1977-03-10',
    bloodGroup: 'O',
    rhFactor: '+',
    maritalStatus: 'Married',
    age: { years: 45, months: 2, days: 13 },
    phoneResidence: '555-321-7890',
    mobilePhone: '555-987-4567',
    emailAddress: 'michael.johnson@example.com',
    emergencyContactName: 'Sarah Johnson',
    emergencyContactPhoneNumber: '555-555-5555',
    family: ['Sarah Johnson', 'David Johnson'],
    currentIllnesses: ['Back Pain', 'Muscle Strain', 'Sprain'],
    previousIllnesses: ['Sciatica', 'Arthritis'],
    specificAllergies: ['Shellfish', 'Dairy'],
    currentMedications: ['Naproxen', 'Muscle Relaxants'],
    pastMedications: ['Ibuprofen', 'Chondroitin'],
    labReports: [
      {
        report: 'Lab report text here',
        photo: 'https://i.imgur.com/kCtVNDR.png',
        radiologyVideo: 'https://www.youtube.com/embed/tW2SjlMGj0Q?si=ksQ6sKB0XmSz9z46',
        mriTracingImages: 'https://i.imgur.com/Fv45Hji.png'
      }
    ],
    xRays: ['https://i.imgur.com/onW1Xuv.png', 'https://i.imgur.com/KcsHQbA.png'],
    doctorVisits: ['2022-01-15T08:00:00Z', '2022-02-25T09:30:00Z'],
    vaccinations: ['2022-03-30T10:45:00Z', '2022-04-20T11:15:00Z'],
    appointmentTimes: ['2022-05-25T12:30:00Z', '2022-06-05T13:00:00Z']
  },
  {
    id: 'https://i.imgur.com/3AlDV7v.png',
    name: 'Amelia Brown',
    firstName: 'Amelia',
    middleName: 'Grace',
    lastName: 'Brown',
    gender: 'Female',
    dateOfBirth: '1987-09-05',
    bloodGroup: 'B',
    rhFactor: '-',
    maritalStatus: 'Divorced',
    age: { years: 35, months: 5, days: 21 },
    phoneResidence: '555-987-6543',
    mobilePhone: '555-123-4567',
    emailAddress: 'amelia.brown@example.com',
    emergencyContactName: 'William Brown',
    emergencyContactPhoneNumber: '555-555-5555',
    family: ['William Brown', 'Olivia Brown'],
    currentIllnesses: ['Migraine', 'Headache', 'Tension'],
    previousIllnesses: ['Vertigo', 'Fibromyalgia'],
    specificAllergies: ['Latex', 'Sulfites'],
    currentMedications: ['Sumatriptan', 'Muscle Relaxants', 'Water'],
    pastMedications: ['Topiramate', 'Meloxicam'],
    labReports: [
      {
        report: 'Lab report text here',
        photo: 'https://i.imgur.com/kCtVNDR.png',
        radiologyVideo: 'https://www.youtube.com/embed/tW2SjlMGj0Q?si=ksQ6sKB0XmSz9z46',
        mriTracingImages: 'https://i.imgur.com/Fv45Hji.png'
      }
    ],
    xRays: ['https://i.imgur.com/onW1Xuv.png', 'https://i.imgur.com/KcsHQbA.png'],
    doctorVisits: ['2022-01-20T08:00:00Z', '2022-02-28T09:30:00Z'],
    vaccinations: ['2022-03-05T10:45:00Z', '2022-04-25T11:15:00Z'],
    appointmentTimes: ['2022-05-30T12:30:00Z', '2022-06-10T13:00:00Z']
  },
  {
    id: 'https://i.imgur.com/3AlDV7v.png',
    name: 'David Wilson',
    firstName: 'David',
    middleName: 'James',
    lastName: 'Wilson',
    gender: 'Male',
    dateOfBirth: '1994-12-20',
    bloodGroup: 'AB',
    rhFactor: '+',
    maritalStatus: 'Single',
    age: { years: 28, months: 5, days: 16 },
    phoneResidence: '555-789-1234',
    mobilePhone: '555-456-9876',
    emailAddress: 'david.wilson@example.com',
    emergencyContactName: 'Sarah Wilson',
    emergencyContactPhoneNumber: '555-555-5555',
    family: ['Sarah Wilson', 'Emily Wilson'],
    currentIllnesses: ['Allergy', 'Hay Fever', 'Skin Rash'],
    previousIllnesses: ['Eczema', 'Asthma'],
    specificAllergies: ['Pet Dander', 'Pollen'],
    currentMedications: ['Loratadine', 'Corticosteroids'],
    pastMedications: ['Diphenhydramine', 'Albuterol'],
    labReports: [
      {
        report: 'Lab report text here',
        photo: 'https://i.imgur.com/kCtVNDR.png',
        radiologyVideo: 'https://www.youtube.com/embed/tW2SjlMGj0Q?si=ksQ6sKB0XmSz9z46',
        mriTracingImages: 'https://i.imgur.com/Fv45Hji.png'
      }
    ],
    xRays: ['https://i.imgur.com/onW1Xuv.png', 'https://i.imgur.com/KcsHQbA.png'],
    doctorVisits: ['2022-01-25T08:00:00Z', '2022-02-10T09:30:00Z'],
    vaccinations: ['2022-03-10T10:45:00Z', '2022-04-30T11:15:00Z'],
    appointmentTimes: ['2022-05-05T12:30:00Z', '2022-06-15T13:00:00Z']
  },
  {
    id: 'https://i.imgur.com/3AlDV7v.png',
    name: 'Sarah Davis',
    firstName: 'Sarah',
    middleName: 'Elizabeth',
    lastName: 'Davis',
    gender: 'Female',
    dateOfBirth: '1972-08-12',
    bloodGroup: 'A',
    rhFactor: '-',
    maritalStatus: 'Married',
    age: { years: 50, months: 9, days: 15 },
    phoneResidence: '555-456-7890',
    mobilePhone: '555-789-1234',
    emailAddress: 'sarah.davis@example.com',
    emergencyContactName: 'John Davis',
    emergencyContactPhoneNumber: '555-555-5555',
    family: ['John Davis', 'Emily Davis'],
    currentIllnesses: ['Arthritis', 'Joint Pain', 'Inflammation'],
    previousIllnesses: ['Osteoporosis', 'Fibromyalgia'],
    specificAllergies: ['Latex', 'Gluten'],
    currentMedications: ['Celecoxib', 'Prednisone'],
    pastMedications: ['Ibuprofen', 'Methotrexate'],
    labReports: [
      {
        report: 'Lab report text here',
        photo: 'https://i.imgur.com/kCtVNDR.png',
        radiologyVideo: 'https://www.youtube.com/embed/tW2SjlMGj0Q?si=ksQ6sKB0XmSz9z46',
        mriTracingImages: 'https://i.imgur.com/Fv45Hji.png'
      }
    ],
    xRays: ['https://i.imgur.com/onW1Xuv.png', 'https://i.imgur.com/KcsHQbA.png'],
    doctorVisits: ['2022-02-01T08:00:00Z', '2022-02-05T09:30:00Z'],
    vaccinations: ['2022-03-15T10:45:00Z', '2022-04-05T11:15:00Z'],
    appointmentTimes: ['2022-05-10T12:30:00Z', '2022-06-20T13:00:00Z']
  },
  {
    id: 'https://i.imgur.com/3AlDV7v.png',
    name: 'Olivia Martinez',
    firstName: 'Olivia',
    middleName: 'Rose',
    lastName: 'Martinez',
    gender: 'Female',
    dateOfBirth: '1980-06-08',
    bloodGroup: 'B',
    rhFactor: '-',
    maritalStatus: 'Single',
    age: { years: 42, months: 10, days: 4 },
    phoneResidence: '555-987-4567',
    mobilePhone: '555-789-1234',
    emailAddress: 'olivia.martinez@example.com',
    emergencyContactName: 'Daniel Martinez',
    emergencyContactPhoneNumber: '555-555-5555',
    family: ['Daniel Martinez', 'Sophia Martinez'],
    currentIllnesses: ['Anxiety', 'Stress', 'Depression'],
    previousIllnesses: ['Panic Disorder', 'Insomnia'],
    specificAllergies: ['Peanuts', 'Soy'],
    currentMedications: ['Sertraline', 'Buspirone'],
    pastMedications: ['Citalopram', 'Escitalopram'],
    labReports: [
      {
        report: 'Lab report text here',
        photo: 'https://i.imgur.com/kCtVNDR.png',
        radiologyVideo: 'https://www.youtube.com/embed/tW2SjlMGj0Q?si=ksQ6sKB0XmSz9z46',
        mriTracingImages: 'https://i.imgur.com/Fv45Hji.png'
      }
    ],
    xRays: ['https://i.imgur.com/onW1Xuv.png', 'https://i.imgur.com/KcsHQbA.png'],
    doctorVisits: ['2022-02-05T08:00:00Z', '2022-02-15T09:30:00Z'],
    vaccinations: ['2022-03-20T10:45:00Z', '2022-04-10T11:15:00Z'],
    appointmentTimes: ['2022-05-15T12:30:00Z', '2022-06-25T13:00:00Z']
  },
  {
    id: 'https://i.imgur.com/3AlDV7v.png',
    name: 'Ethan Clark',
    firstName: 'Ethan',
    middleName: 'Michael',
    lastName: 'Clark',
    gender: 'Male',
    dateOfBirth: '1985-04-17',
    bloodGroup: 'O',
    rhFactor: '+',
    maritalStatus: 'Single',
    age: { years: 39, months: 6, days: 17 },
    phoneResidence: '555-789-1234',
    mobilePhone: '555-123-4567',
    emailAddress: 'ethan.clark@example.com',
    emergencyContactName: 'Emma Clark',
    emergencyContactPhoneNumber: '555-555-5555',
    family: ['Emma Clark', 'Aiden Clark'],
    currentIllnesses: ['Hypertension', 'High Cholesterol', 'Heart Disease'],
    previousIllnesses: ['Stroke', 'Arrhythmia'],
    specificAllergies: ['Shellfish', 'Eggs'],
    currentMedications: ['Lisinopril', 'Atorvastatin'],
    pastMedications: ['Amlodipine', 'Simvastatin'],
    labReports: [
      {
        report: 'Lab report text here',
        photo: 'https://i.imgur.com/kCtVNDR.png',
        radiologyVideo: 'https://www.youtube.com/embed/tW2SjlMGj0Q?si=ksQ6sKB0XmSz9z46',
        mriTracingImages: 'https://i.imgur.com/Fv45Hji.png'
      }
    ],
    xRays: ['https://i.imgur.com/onW1Xuv.png', 'https://i.imgur.com/KcsHQbA.png'],
    doctorVisits: ['2022-02-10T08:00:00Z', '2022-02-20T09:30:00Z'],
    vaccinations: ['2022-03-25T10:45:00Z', '2022-04-15T11:15:00Z'],
    appointmentTimes: ['2022-05-20T12:30:00Z', '2022-06-30T13:00:00Z']
  },
  {
    id: 'https://i.imgur.com/3AlDV7v.png',
    name: 'Sophia Lee',
    firstName: 'Sophia',
    middleName: 'Ava',
    lastName: 'Lee',
    gender: 'Female',
    dateOfBirth: '1979-07-23',
    bloodGroup: 'A',
    rhFactor: '-',
    maritalStatus: 'Divorced',
    age: { years: 43, months: 11, days: 12 },
    phoneResidence: '555-789-1234',
    mobilePhone: '555-321-7890',
    emailAddress: 'sophia.lee@example.com',
    emergencyContactName: 'Jacob Lee',
    emergencyContactPhoneNumber: '555-555-5555',
    family: ['Jacob Lee', 'Oliver Lee'],
    currentIllnesses: ['Diabetes', 'Obesity', 'High Blood Pressure'],
    previousIllnesses: ['Gestational Diabetes', 'Insulin Resistance'],
    specificAllergies: ['Peanuts', 'Gluten'],
    currentMedications: ['Metformin', 'Insulin'],
    pastMedications: ['Gliclazide', 'Glipizide'],
    labReports: [
      {
        report: 'Lab report text here',
        photo: 'https://i.imgur.com/kCtVNDR.png',
        radiologyVideo: 'https://www.youtube.com/embed/tW2SjlMGj0Q?si=ksQ6sKB0XmSz9z46',
        mriTracingImages: 'https://i.imgur.com/Fv45Hji.png'
      }
    ],
    xRays: ['https://i.imgur.com/onW1Xuv.png', 'https://i.imgur.com/KcsHQbA.png'],
    doctorVisits: ['2022-02-15T08:00:00Z', '2022-02-25T09:30:00Z'],
    vaccinations: ['2022-03-30T10:45:00Z', '2022-04-20T11:15:00Z'],
    appointmentTimes: ['2022-05-25T12:30:00Z', '2022-06-05T13:00:00Z']
  },
  {
    id: 'https://i.imgur.com/3AlDV7v.png',
    name: 'Aliver Taylor',
    firstName: 'Aliver',
    middleName: 'Benjamin',
    lastName: 'Taylor',
    gender: 'Male',
    dateOfBirth: '1982-11-29',
    bloodGroup: 'B',
    rhFactor: '+',
    maritalStatus: 'Married',
    age: { years: 40, months: 4, days: 3 },
    phoneResidence: '555-321-7890',
    mobilePhone: '555-456-7890',
    emailAddress: 'oliver.taylor@example.com',
    emergencyContactName: 'Emma Taylor',
    emergencyContactPhoneNumber: '555-555-5555',
    family: ['Emma Taylor', 'Ava Taylor'],
    currentIllnesses: ['Lung Disease', 'Asthma', 'Bronchitis'],
    previousIllnesses: ['Pneumonia', 'Emphysema'],
    specificAllergies: ['Dust', 'Pollen'],
    currentMedications: ['Albuterol', 'Corticosteroids'],
    pastMedications: ['Prednisone', 'Montelukast'],
    labReports: [
      {
        report: 'Lab report text here',
        photo: 'https://i.imgur.com/kCtVNDR.png',
        radiologyVideo: 'https://www.youtube.com/embed/tW2SjlMGj0Q?si=ksQ6sKB0XmSz9z46',
        mriTracingImages: 'https://i.imgur.com/Fv45Hji.png'
      }
    ],
    xRays: ['https://i.imgur.com/onW1Xuv.png', 'https://i.imgur.com/KcsHQbA.png'],
    doctorVisits: ['2022-02-20T08:00:00Z', '2022-02-28T09:30:00Z'],
    vaccinations: ['2022-03-05T10:45:00Z', '2022-04-25T11:15:00Z'],
    appointmentTimes: ['2022-05-10T12:30:00Z', '2022-06-20T13:00:00Z']
  }
];

export default patients;